import Vue from 'vue'
import App from './App.vue'
import router from './router' 
Vue.config.productionTip = false


// main.js
import API from 'syncobox-shared-api'



//設定API伺服器網址
API.config.token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IkFCZXFQVjYwVG1fVnRPc3BraGlRY0EiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE2MDQ5NzE5MTgsImV4cCI6MTYwNDk3NTUxOCwiaXNzIjoiaHR0cHM6Ly9pZGVudGl0eS1kZXYuc3luY29ib3guY29tIiwiYXVkIjoicGFubzphbGwiLCJjbGllbnRfaWQiOiJzeW5jb2JveC1hcGktc3dhZ2dlciIsInN1YiI6ImI4MDZiMTZmLWEzY2YtNDJkZS1iN2Q4LWFjOGQzZTgyYzk4MSIsImF1dGhfdGltZSI6MTYwNDk3MTkxOCwiaWRwIjoibG9jYWwiLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IkFZN0dFTlFERkhQQk8zVVZYWUlXMkhZTjdVVVlLM01aIiwiZm9yZ2VfZXhwaXJlc19kYXRlIjoiMDAwMeW5tDHmnIgx5pelIOaYn-acn-S4gCIsInByZWZlcnJlZF91c2VybmFtZSI6InF3ZXJvbzA1MjhAZ21haWwuY29tIiwibmFtZSI6InF3ZXJvbzA1MjhAZ21haWwuY29tIiwiZW1haWwiOiJxd2Vyb28wNTI4QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI4MDZiMTZmLWEzY2YtNDJkZS1iN2Q4LWFjOGQzZTgyYzk4MSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJxd2Vyb28wNTI4QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InF3ZXJvbzA1MjhAZ21haWwuY29tIiwic2NvcGUiOlsicGFubzphbGwiXSwiYW1yIjpbInB3ZCJdfQ.DIn4UiamMBiMvBMjPTstHc8zPrhHM5Hx1rsToG4fbUmFsjw0cnKUCj-AMw2Avz6C0x-crgc4qG7vtvgc3xYBQyCoKOPzuAzTWCl-CSpBIwRiHKYArvoOzziEyf1Ow-KGqXQ0qnl9Y0-9R0dCqSBOtVL0QDGfEpNgJXxSVJzpBlHjS60ddE8RQVC1J1D4uaU4QX7o71sBeZ0OCssgLnFQwrJ2TBQuxGcPbfwExB5y4uk4t0rQnl1n51LNmYEfRDeBjZEGF2BaSoilMkwhLC_SbvypM02_qcXrAX3iozXtdhZhn7fknigQRvV8hNVw_1Nf-BFkI3wUi7ofLK-yfX8hMQ";
API.config.mainBaseUrl = process.env.VUE_APP_MAIN_BASE_URL
API.config.bimBaseUrl = process.env.VUE_APP_BIM_BASE_URL
Vue.prototype.$API = API


new Vue({
  router,
  render: h => h(App)
}).$mount('#app')
